version: '3.9'

services:
  web:
    container_name: backend
    image: backend
    build: .
    ports:
      - "8080:8080"
    command: >
      bash -c "
        until pg_isready -h db -p 5432; do
          echo 'Waiting for Postgres to be ready...';
          sleep 5;
        done;
        service cron start &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py crontab add &&
        python manage.py runserver 0.0.0.0:8080"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:
