# Generated by Django 5.0.3 on 2024-06-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('was_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(default='info', max_length=255)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
