# Generated by Django 5.0.3 on 2024-06-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_updated_at_and_more'),
        ('product', '0005_product_previous_price_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationnewinranking',
            name='higher_ranked_products',
        ),
        migrations.RemoveField(
            model_name='notificationnewinranking',
            name='provider_product',
        ),
        migrations.CreateModel(
            name='HigherRankedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_ranked_products', models.ManyToManyField(related_name='nr_ranked_notifications', to='product.product')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nr_provider_notifications', to='product.product')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nr_products', to='notifications.notificationnewinranking')),
            ],
            options={
                'db_table': 'notification_higher_ranked_products',
            },
        ),
    ]
