# Generated by Django 5.0.3 on 2024-06-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_higherrankedproducts_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='higherrankedproducts',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nr_products', to='notifications.notification'),
        ),
        migrations.DeleteModel(
            name='NotificationNewInRanking',
        ),
    ]
