# Generated by Django 5.0.3 on 2024-06-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_spy', '0002_rename_productupdate_productsupdatelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupdatelogs',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
