# Generated by Django 5.0.3 on 2024-07-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_spy', '0003_alter_productsupdatelogs_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupdatelogs',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
