# Generated by Django 5.0.3 on 2024-04-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
