# Generated by Django 5.0.3 on 2024-04-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_comparisonzone_comparison_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonzone',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
