# Generated by Django 5.0.3 on 2024-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_shop_product_old_price_product_previous_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='previous_price_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
