# Generated by Django 5.0.3 on 2024-07-01 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_previous_price_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.manufacture'),
        ),
    ]
