# Generated by Django 5.0.3 on 2024-04-12 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_last_updated_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
