# Generated by Django 5.0.3 on 2024-07-15 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_manufacture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryShop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.categoryshop')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_shops', to='product.shop')),
            ],
            options={
                'db_table': 'category_shop',
            },
        ),
    ]
