# Generated by Django 5.0.3 on 2024-07-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_categoryshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_shops', to='product.shop'),
        ),
    ]
