# Generated by Django 5.0.3 on 2024-07-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_categories_shop_provider_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
