# Generated by Django 5.0.3 on 2024-07-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='date_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
