# Generated by Django 5.0.3 on 2024-07-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacture_shops', to='product.shop'),
        ),
    ]
