# Generated by Django 5.0.3 on 2024-07-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_shop_date_last_update'),
        ('product', '0012_product_description'),
    ]

    operations = [
    ]
